### ISSUE TITLE
Missing transitive dependencies in paket.lock

### ISSUE THREAD

**Issue by tomzo** [ai-traders/BaGet#12]
When using paket with baget, it skips all transitive dependencies.
`paket.lock` has only direct dependencies.

Concerns packages both from cache and private feed.

Probably related to https://github.com/loic-sharma/BaGet/issues/109

**Comment by tomzo** [comment]
Most likely missing `dependencyGroups` in CatalogEntry. https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource#catalog-entry

**Comment by rong0312** [comment]
I have PR regards this issue, adding dependencyGroups

**Comment by tomzo** [comment]
Thanks, I saw your PR.
I am working on a fix. It is slightly different in this fork, because I have V2 and implemented cache. I also need tests for this.

**Comment by tomzo** [comment]
Released in 0.2.1
